version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nerkhin-net

  backend:
    container_name: nerkhin-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:local
    ports:
      - "8084:8084"
    volumes:
      - server-data:/data
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - nerkhin-net

  frontend:
    container_name: nerkhin-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:local
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - nerkhin-net

volumes:
  postgres-data:
  server-data:

networks:
  nerkhin-net:
    driver: bridge
