export const userMessages = {
    pageTitle: 'مدیریت کاربران',
    fullName: 'نام و نام خانوادگی',
    phone: 'شماره تماس',
    userType: 'نوع کاربر',
    subscriptionStatus: 'وضعیت اشتراک',
    daysRemaining: 'روزهای باقیمانده',
    totalPaid: 'مجموع پرداختی',
    actions: 'عملیات',
    retailer: 'خرده فروش',
    wholesaler: 'عمده فروش',
    active: 'فعال',
    inactive: 'غیرفعال',
    noSubscription: 'بدون اشتراک',
    filter: 'فیلتر',
    allUsers: 'همه کاربران',
    allStatuses: 'همه وضعیت‌ها',
    hasSubscription: 'دارای اشتراک',
    noUsersFound: 'کاربری با این مشخصات یافت نشد.',
    grantSubscription: 'اعطای اشتراک',
    grantModalTitle: 'اعطای اشتراک به کاربر',
    daysToGrant: 'تعداد روز',
    grant: 'اعطا',
    cancel: 'انصراف',
    subscriptionGrantedSuccess: 'اشتراک با موفقیت اعطا شد.',
    errorOccurred: 'خطایی رخ داد. لطفا دوباره تلاش کنید.',
    loginAsUser: 'ورود به صفحه کاربری',
  };