CREATE TABLE IF NOT EXISTS user_t (
  id              BIGSERIAL     NOT NULL PRIMARY KEY,
  phone           VARCHAR(20)   NOT NULL UNIQUE,
  city_id         BIGINT        NOT NULL REFERENCES city (id),
  role            SMALLINT      NOT NULL,
  state_c         SMALLINT      NOT NULL,
  full_name       VARCHAR(50)   NOT NULL,
  shop_name       VARCHAR(50),
  shop_address    VARCHAR(250),
  shop_phone1     VARCHAR(20), 
  shop_phone2     VARCHAR(20), 
  shop_phone3     VARCHAR(20), 
  telegram_url    VARCHAR(50),
  instagram_url   VARCHAR(50),
  whatsapp_url    VARCHAR(50),
  website_url     VARCHAR(50),
  image_url 	    VARCHAR(200),
  dollar_price    DECIMAL(28, 6),
  latitude        DECIMAL(28, 6),
  longitude       DECIMAL(28, 6),
  likes_count     INT           NOT NULL,
  products_count  INT           NOT NULL,
  created_at      TIMESTAMP     NOT NULL,
  updated_at      TIMESTAMP     NOT NULL
);